[package]
name = "block"
version = "0.1.0"
authors = ["Denis Bazhenov <dotsid@gmail.com>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
tempdir = "0.3.7"
byteorder = "1.3.4"
clap = "2.33.0"
md5 = "0.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "example"
harness = false
